---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  environments_path: "test/integration/environments"
  roles_path: "test/integration/roles"
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  client_rb:
     environment: skynet_localdev
platforms:
  - name: chef12
    driver:
      gui: true
      customize:
        memory: 2048
        cpus: 2
      vm_hostname: default-chef12
      box: oel73-default-5.1.8
    transport:
      max_ssh_sessions: 1
    provisioner:
      require_chef_omnibus: 12.21.1
  - name: chef13
    driver:
      customize:
        memory: 2048
        cpus: 2
      vm_hostname: default-chef12
      box: oel73-default-5.1.8
    transport:
      max_ssh_sessions: 1
    provisioner:
      require_chef_omnibus: 13.1.31
suites:
  - name: etcd
    run_list:
      - recipe[skynet::core_system]
      - recipe[skynet::prometheus_exporter]
      - recipe[skynet::etcd]
      - role[skynet-etcd-kitchen]
      - role[prometheus-exporter]
      #- role[oradev]
    verifier:
      inspec_tests:
        - path: test/integration/default/etcd/default_spec.rb
  - name: master
    run_list:
      - recipe[skynet::core_system]
      - recipe[skynet::prometheus_exporter]
      - recipe[skynet::etcd]
      - recipe[skynet::kubernetes_master]
      - role[skynet-etcd-kitchen]
      - role[skynet-master]
      #- role[oradev]
    verifier:
      inspec_tests:
        - path: test/integration/default/etcd/default_spec.rb
        - path: test/integration/default/kubernetes/master_spec.rb
  - name: full
    run_list:
      #- recipe[skynet_kitchen_helper::uek4]
      - recipe[skynet::etcd]
      - recipe[skynet::kubernetes_master]
      #- recipe[skynet::kubernetes_worker]
      - recipe[skynet_kitchen_helper::docker]
      #- recipe[skynet::trust_ca]
      - role[skynet-etcd-kitchen]
      - role[skynet-master]
      #- role[skynet-worker]
    verifier:
      inspec_tests:
        - path: test/integration/default/etcd/default_spec.rb
        - path: test/integration/default/kubernetes/master_spec.rb
        - path: test/integration/default/kubernetes/worker_spec.rb
