default['skynet']['etcd']['user']='etcd'
default['skynet']['etcd']['group']='etcd'
default['skynet']['etcd']['version']='3.1.2-1'
default['skynet']['etcd']['certificate_data_bag_info']=[]
#e.g ::['certificate_data_bag_info']=[{ key: 'server.cert', dbag_name: 'certificates', dbag_item: 'skynet_etcd', path: '/tmp/cert.pem'  }]
default['skynet']['etcd']['peer_port']=2380
default['skynet']['etcd']['client_port']=2379
default['skynet']['etcd']['tls_enabled']=false
default['skynet']['etcd']['name']=''#localhost'#'localnode'
default['skynet']['etcd']['heartbeat-interval']=200
default['skynet']['etcd']['cert-file']=''
default['skynet']['etcd']['key-file']=''
default['skynet']['etcd']['peer-cert-file']=''
default['skynet']['etcd']['peer-key-file']=''
default['skynet']['etcd']['trusted-ca-file']=''
default['skynet']['etcd']['peer-trusted-ca-file']=''
default['skynet']['etcd']['initial-advertise-peer-urls']='' # 'http://localhost:2380'
default['skynet']['etcd']['listen-peer-urls']=''            # will render 'http://localhost:2380' depending on tls_enabled
default['skynet']['etcd']['listen-client-urls']=''          #'http://localhost:2379'
default['skynet']['etcd']['advertise-client-urls']=''       #'http://localhost:2379'
default['skynet']['etcd']['initial-cluster-token']='etcd-cluster-0'
default['skynet']['etcd']['initial-cluster']="default-chef12=http://default-chef12:2380" # Needs to be configured manually
default['skynet']['etcd']['initial-cluster-state']='new'
default['skynet']['etcd']['data-dir']='/var/lib/etcd'
